language: go

go: tip

before_install:
 - uname -a
 - sudo apt-get update -qq
 - sudo apt-get install -qq exuberant-ctags
 - git clone https://github.com/ruben2020/codequery.git $HOME/codequery

before_script:
 - export PATH=$HOME/gopath/bin:$PATH

script: go install github.com/ruben2020/tags2uml

after_script:
 - tags2uml --ver
 - tags2uml --help
 - cd $HOME/codequery
 - ctags --fields=+latinK -R
 - tags2uml --infile tags --outfile codequery.dot
 - cat codequery.dot

notifications:
  email:
    - ruben2020-git@users.sourceforge.net
  on_success: change
  on_failure: always

